# Inserção dos dados de exemplo

INSERT INTO artigo (tituloartigo, conteudoartigo) VALUES 
	("Artigo 01", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent semper diam quis fermentum suscipit. Cras ut egestas turpis, quis euismod mi. Proin interdum velit vitae risus auctor, ac fermentum mauris faucibus. Suspendisse dictum arcu urna, vel convallis velit euismod in. Nullam volutpat eros eu nunc volutpat ultrices. Integer urna est, consequat vitae porttitor in, condimentum vel nibh. Proin vel elementum felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla posuere, dui ultricies scelerisque interdum, libero mi consequat lectus, in iaculis turpis lectus in massa. Sed fermentum lorem diam. Donec placerat ornare ipsum et convallis. Vivamus sodales, libero ornare gravida eleifend, purus ex eleifend eros, a mattis tellus dui non metus. Pellentesque cursus leo ex, sit amet ornare tortor placerat vel. Nunc congue pretium felis, vel tempus elit gravida non."),
    ("Artigo 02", "Praesent vel dictum lectus, vel mattis erat. Mauris ut venenatis turpis. Donec aliquam tempus ligula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse interdum lorem a placerat consectetur. Proin lobortis molestie nibh at consequat. Integer non ullamcorper mi. Nunc ornare dui sed odio congue, eu dapibus felis egestas. Vivamus tempor in enim eget facilisis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum nec pretium neque. Nulla facilisis nec velit a posuere. Sed convallis quam lorem. Quisque ut interdum nisi. Integer rutrum neque vitae elit condimentum, ut hendrerit nisi pretium."),
    ("Artigo 03", "Donec id ipsum quis enim sodales accumsan. Quisque luctus sapien vitae lacus dapibus, a eleifend purus sodales. Sed malesuada sollicitudin urna, sed varius nunc malesuada sed. Donec eu ipsum est. Nulla sed pellentesque urna. Phasellus sit amet est id lacus rhoncus pharetra ac in odio. Nullam congue quam sit amet orci vestibulum maximus. Praesent suscipit felis in efficitur vestibulum. Cras iaculis, urna vitae egestas tempus, nisl odio finibus urna, quis eleifend arcu ipsum sed sem. Nunc ornare mi nec nibh ullamcorper maximus sed ut nunc. Vestibulum viverra turpis eget sapien lacinia, vitae pretium dui maximus. Fusce tempor condimentum rutrum."),
    ("Artigo 04", "Quisque hendrerit enim a egestas ultrices. Nam non laoreet enim, at interdum metus. Nullam congue dui non dignissim iaculis. Praesent ultricies erat faucibus felis imperdiet, eu bibendum velit volutpat. Suspendisse placerat erat et commodo efficitur. Cras odio lectus, luctus non malesuada in, bibendum sit amet dolor. Duis id mauris sit amet nulla lobortis hendrerit. Curabitur ac nulla eu erat luctus bibendum. Vivamus nisi sem, rhoncus id laoreet quis, mollis nec ante. Fusce vitae est nisl. Nullam at nibh ut nibh mollis lacinia. Curabitur scelerisque mauris at nibh maximus tempor. Integer eu est eget elit convallis rutrum nec ac nunc."),
    ("Artigo 05", "Suspendisse rhoncus aliquet volutpat. Sed feugiat, tortor sed pellentesque vestibulum, nunc elit suscipit ex, a lacinia orci arcu at lectus. Nullam lacinia, est ut posuere faucibus, augue ligula porttitor sapien, vitae dictum lacus massa sed tellus. Aliquam erat volutpat. Aliquam tempor tellus et tortor hendrerit suscipit. Vivamus commodo lacus libero. Cras vitae ligula vitae massa efficitur viverra. Fusce vel sem mattis, tincidunt massa id, ornare nulla. Maecenas congue at orci vel rutrum. Curabitur et metus ligula. Proin interdum, arcu sed gravida luctus, tortor nisl fringilla velit, in fringilla magna est non metus. Nulla in velit nisl."),
    ("Artigo 06", "Nam sit amet pretium dolor, nec ultricies nulla. Duis non augue in nulla aliquet posuere malesuada id sapien. Cras tristique massa et nibh dictum accumsan. Morbi at elit mattis, tristique ipsum nec, varius nibh. Vestibulum ut tincidunt tortor, sed vehicula mi. Mauris rhoncus dolor a tincidunt mattis. Morbi pharetra urna pharetra, finibus ante iaculis, consequat purus. Quisque varius tortor vitae condimentum tincidunt. Maecenas eget venenatis enim. Aenean rhoncus cursus enim, et iaculis lectus. Ut a metus metus. Morbi ac arcu vitae turpis consectetur rutrum. Proin at lorem massa. Nam pulvinar sapien ac imperdiet mollis."),
    ("Artigo 07", "Vestibulum consectetur arcu sit amet nunc posuere dapibus. Donec porttitor augue erat, id hendrerit justo congue non. In pretium, nisl nec sodales tincidunt, leo ante convallis augue, eu tincidunt lorem turpis vitae ipsum. Aenean rutrum at urna quis sagittis. Aenean ornare neque eget nisl vehicula malesuada. Suspendisse sem nisl, bibendum non orci sed, vulputate tincidunt enim. Integer ut magna nec magna laoreet volutpat a et ex. Nam vitae quam nec ligula interdum ultrices. In auctor sit amet mauris consectetur feugiat. Pellentesque fermentum cursus suscipit. Suspendisse potenti. In congue luctus gravida. Donec id magna non lorem blandit mattis."),
    ("Artigo 08", "Pellentesque sem lorem, congue vitae erat eu, mollis pharetra diam. Maecenas consequat mi ut lacus pellentesque elementum. Vestibulum aliquet eleifend quam sed hendrerit. Maecenas interdum elit sit amet risus rutrum, rhoncus pretium purus vehicula. Vivamus bibendum orci sed vehicula tempor. Vivamus et metus vel tortor interdum dictum. Ut convallis et nisl in eleifend. Phasellus magna quam, aliquam vel euismod vel, bibendum sit amet arcu. Sed facilisis auctor est quis fringilla. Maecenas efficitur, metus elementum volutpat ullamcorper, velit ligula finibus dolor, a vestibulum neque nisl ac lorem. Phasellus sodales pharetra nisi nec eleifend. Quisque feugiat malesuada ullamcorper."),
    ("Artigo 09", "Cras dolor diam, aliquam vitae dui vel, fermentum ultrices est. Mauris elementum sapien vel diam lacinia semper. Maecenas molestie sem eget ligula tempor cursus. Mauris consequat odio sed molestie volutpat. Proin sodales ultricies est vel bibendum. Vivamus consectetur, ipsum et tincidunt finibus, neque lorem aliquet erat, id varius dolor libero nec odio. In hac habitasse platea dictumst. Etiam vel ante nisi. Sed odio diam, vestibulum non tincidunt eu, euismod eu nulla. Suspendisse dapibus condimentum ultricies. In rhoncus ligula eu sem lacinia lobortis. Nam ultrices dapibus orci. Duis vel elementum nisi. Pellentesque non dignissim urna, vitae vestibulum mauris. Fusce neque nisl, ultrices sed urna a, cursus porta ex. Nam laoreet lobortis turpis vestibulum malesuada."),
    ("Artigo 10", "Nulla sit amet pretium felis, eget varius odio. Praesent sagittis placerat eros, at aliquet nisl aliquet ut. Nunc congue enim eu quam molestie, et sollicitudin diam lacinia. In eget suscipit turpis, nec malesuada quam. Phasellus sollicitudin felis sed nisi viverra, in commodo eros consectetur. Praesent et mauris metus. Pellentesque gravida massa vitae metus venenatis, id sagittis est cursus. Nullam ac convallis magna. Pellentesque laoreet eget est sed condimentum. Vivamus a luctus nulla. Aliquam faucibus mollis erat, in ornare ex euismod ac."),
    ("Artigo 11", "Praesent ultricies ante cursus justo faucibus, non sodales erat accumsan. Nam enim mi, eleifend non diam sit amet, molestie luctus purus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed tempor quam purus, ac euismod erat accumsan vel. Nunc tellus erat, feugiat a luctus eu, pretium quis felis. In porta consectetur lectus, ut vulputate purus sagittis sed. Duis mollis, urna non laoreet faucibus, mauris elit egestas lacus, eu laoreet turpis nisi a ante. Vivamus maximus porta iaculis. Maecenas tempor luctus lectus, eu tristique elit tincidunt vitae. Nulla malesuada arcu elementum, cursus neque in, dapibus erat. Nunc accumsan et leo eget porttitor. Aenean lacinia molestie magna eu hendrerit. Proin vehicula vestibulum mauris condimentum rutrum. Ut dignissim luctus diam ut euismod. Nullam luctus, tellus nec pretium sagittis, enim lorem fermentum ex, in eleifend risus tortor vel velit. Nam a dapibus mauris."),
    ("Artigo 12", "Morbi ac ligula sollicitudin, pharetra sem imperdiet, hendrerit ex. Morbi vitae libero orci. Pellentesque mollis diam vel lectus pulvinar commodo. Nunc eget venenatis risus. Pellentesque lorem tortor, accumsan pellentesque finibus sit amet, tincidunt a nisi. Sed non arcu in justo imperdiet rutrum. Morbi vel velit interdum lorem ullamcorper varius. Sed ut blandit arcu. Sed varius magna dui, eget auctor ipsum auctor in. Maecenas sapien libero, finibus vitae egestas eget, tempus sit amet urna. Sed in tristique neque. Praesent porttitor fringilla velit et posuere. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque ut neque pharetra, vestibulum ligula at, varius magna. Donec et enim vitae tortor porta dictum sit amet nec mauris."),
    ("Artigo 13", "Sed ac vestibulum sem. Vestibulum porttitor mi vitae mauris efficitur lobortis eget sollicitudin tortor. Integer nec nunc luctus, venenatis est sollicitudin, scelerisque erat. Maecenas eget neque in justo vulputate placerat. Integer viverra arcu vitae felis blandit, congue hendrerit tortor lacinia. Ut quis orci nisi. Donec id purus eros. Quisque ultricies vitae nibh quis faucibus. Nullam ullamcorper fringilla metus, sed ullamcorper metus cursus eleifend. Aenean ut sem interdum, fringilla sapien ultricies, porta tellus."),
    ("Artigo 14", "Quisque dignissim ipsum ac felis malesuada eleifend. Donec vel leo ultrices mauris sodales convallis. Fusce pellentesque, est eu aliquet euismod, lorem nisi dictum felis, id malesuada dolor risus eget enim. In et facilisis turpis. Duis at nisl eget sem vehicula efficitur vitae vel justo. Etiam at efficitur arcu, ut molestie nisl. In hac habitasse platea dictumst. Proin euismod metus rhoncus, hendrerit nisl nec, pretium nulla. Morbi dolor quam, varius eu hendrerit sit amet, condimentum sit amet arcu. Praesent consequat purus placerat finibus imperdiet. Vivamus euismod, sem vitae molestie placerat, metus mi tincidunt nisi, at accumsan lectus nisi id dolor."),
    ("Artigo 15", "Donec congue blandit magna, vel porta est convallis eget. Suspendisse ut quam ac sem cursus hendrerit id at tortor. Aenean laoreet dolor eu magna malesuada, ut commodo dui feugiat. Etiam mattis, nulla id tincidunt consequat, augue ligula efficitur elit, ut vulputate nibh turpis sit amet ex. Vestibulum eget facilisis tortor, vitae hendrerit sem. Proin nec lobortis ligula. Nunc pretium, mi ac mattis volutpat, mauris massa blandit lectus, ut vulputate erat libero vel justo. Duis at semper massa, eget rhoncus mi. Maecenas pulvinar eros sit amet placerat ullamcorper. Donec sapien lectus, ultricies et condimentum ac, luctus vel elit. Nulla volutpat sagittis erat. Etiam eget diam pharetra, porta velit nec, posuere ex.");
    
SELECT * FROM artigo;

INSERT INTO comentario (conteudocomentario, aceito, idartigo) VALUES 
	("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent semper diam quis fermentum suscipit. Cras ut egestas turpis, quis euismod mi.", "0", "1"),
    ("Proin interdum velit vitae risus auctor, ac fermentum mauris faucibus.", "0", "1"),
    ("Suspendisse dictum arcu urna, vel convallis velit euismod in. Nullam volutpat eros eu nunc volutpat ultrices.", "0", "1"),
    ("Anteger urna est, consequat vitae porttitor in, condimentum vel nibh. Proin vel elementum felis. Interdum et malesuada fames ac ante ipsum primis in faucibus.", "0", "1"),
    ("Nulla posuere, dui ultricies scelerisque interdum, libero mi consequat lectus, in iaculis turpis lectus in massa. Sed fermentum lorem diam.", "0", "2"),
    ("Donec placerat ornare ipsum et convallis. Vivamus sodales, libero ornare gravida eleifend, purus ex eleifend eros, a mattis tellus dui non metus.", "0", "2"),
    ("Pellentesque cursus leo ex, sit amet ornare tortor placerat vel. Nunc congue pretium felis, vel tempus elit gravida non.", "0", "2"),
    ("Praesent vel dictum lectus, vel mattis erat. Mauris ut venenatis turpis. Donec aliquam tempus ligula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", "0", "3"),
    ("Suspendisse interdum lorem a placerat consectetur. Proin lobortis molestie nibh at consequat. Integer non ullamcorper mi. Nunc ornare dui sed odio congue, eu dapibus felis egestas. ", "0", "3"),
    ("Vivamus tempor in enim eget facilisis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum nec pretium neque.", "0", "3"),
    ("Nulla facilisis nec velit a posuere. Sed convallis quam lorem. Quisque ut interdum nisi. Integer rutrum neque vitae elit condimentum, ut hendrerit nisi pretium.", "0", "11"),
    ("Donec id ipsum quis enim sodales accumsan. Quisque luctus sapien vitae lacus dapibus, a eleifend purus sodales. Sed malesuada sollicitudin urna, sed varius nunc malesuada sed.", "0", "11"),
    ("Donec eu ipsum est. Nulla sed pellentesque urna. Phasellus sit amet est id lacus rhoncus pharetra ac in odio. Nullam congue quam sit amet orci vestibulum maximus.", "0", "11"),
	("Praesent suscipit felis in efficitur vestibulum. Cras iaculis, urna vitae egestas tempus, nisl odio finibus urna, quis eleifend arcu ipsum sed sem.", "1", "1"),
    ("Nunc ornare mi nec nibh ullamcorper maximus sed ut nunc. Vestibulum viverra turpis eget sapien lacinia, vitae pretium dui maximus. Fusce tempor condimentum rutrum.", "1", "2"),
    ("Quisque hendrerit enim a egestas ultrices. Nam non laoreet enim, at interdum metus. Nullam congue dui non dignissim iaculis. Praesent ultricies erat faucibus felis imperdiet, eu bibendum velit volutpat.", "1", "2"),
    ("Nam sit amet pretium dolor, nec ultricies nulla. Duis non augue in nulla aliquet posuere malesuada id sapien. Cras tristique massa et nibh dictum accumsan.", "1", "2"),
    ("Morbi at elit mattis, tristique ipsum nec, varius nibh. Vestibulum ut tincidunt tortor, sed vehicula mi. Mauris rhoncus dolor a tincidunt mattis.", "1", "3"),
    ("Morbi pharetra urna pharetra, finibus ante iaculis, consequat purus. Quisque varius tortor vitae condimentum tincidunt. Maecenas eget venenatis enim.", "1", "3"),
    ("Aenean rhoncus cursus enim, et iaculis lectus. Ut a metus metus. Morbi ac arcu vitae turpis consectetur rutrum. Proin at lorem massa. Nam pulvinar sapien ac imperdiet mollis.", "1", "3"),
    ("Vestibulum consectetur arcu sit amet nunc posuere dapibus. Donec porttitor augue erat, id hendrerit justo congue non. In pretium, nisl nec sodales tincidunt, leo ante convallis augue, eu tincidunt lorem turpis vitae ipsum.", "1", "11"),
    ("Aenean rutrum at urna quis sagittis. Aenean ornare neque eget nisl vehicula malesuada. Suspendisse sem nisl, bibendum non orci sed, vulputate tincidunt enim.", "0", "12");
    
SELECT * FROM comentario;

INSERT INTO usuario (email, senha, tipo) VALUES 
	("administrador@gmail.com", "1234", "1"),
    ("joao@gmail.com", "1234", "0"),
    ("augusto@gmail.com", "1234", "0"),
    ("marcelo@gmail.com", "1234", "0"),
    ("douglas@gmail.com", "1234", "0");
    
SELECT * FROM usuario;